### ISSUE TITLE
Failed to build on cygwin x86_64 (gcc version 4.8.2)

### ISSUE THREAD

**Issue by oroppas** [sabel83/mpllibs#2]
Here's a build command:

```
/usr/bin/c++.exe   -DBOOST_TEST_DYN_LINK -DBUILD_MAJOR_VERSION=1 -DBUILD_MINOR_VERSION=0 -DBUILD_PATCH_VERSION=0 -Wall -Werror -pedantic -Wno-variadic-macros -O3 -DNDEBUG -I/home/20089/devel/boost/usr/include -I/home/20089/devel/mpllibs/mpllibs/. -MMD -MT libs/metaparse/test/CMakeFiles/metaparse_test.dir/all_headers.cpp.o -MF "libs/metaparse/test/CMakeFiles/metaparse_test.dir/all_headers.cpp.o.d" -o libs/metaparse/test/CMakeFiles/metaparse_test.dir/all_headers.cpp.o -c /home/20089/devel/mpllibs/mpllibs/libs/metaparse/test/all_headers.cpp
```

Here's an error message:

```
In file included from /home/20089/devel/mpllibs/mpllibs/./mpllibs/metaparse/debug_parsing_error.hpp:9:0,
                 from /home/20089/devel/mpllibs/mpllibs/libs/metaparse/test/all_headers.hpp:20,
                 from /home/20089/devel/mpllibs/mpllibs/libs/metaparse/test/all_headers.cpp:6:
/home/20089/devel/mpllibs/mpllibs/./mpllibs/metaparse/v1/debug_parsing_error.hpp: In constructor ‘mpllibs::metaparse::v1::debug_parsing_error<P, S>::debug_parsing_error()’:
/home/20089/devel/mpllibs/mpllibs/./mpllibs/metaparse/v1/debug_parsing_error.hpp:45:17: error: there are no arguments to ‘exit’ that depend on a template parameter, so a declaration of ‘exit’ must be available [-fpermissive]
           exit(0);
                 ^
/home/20089/devel/mpllibs/mpllibs/./mpllibs/metaparse/v1/debug_parsing_error.hpp:45:17: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
```
